name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checks:
    name: Acceptance Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          enable-pep582: true
      - uses: pre-commit/action@v2.0.3

      # Runs a single command using the runners shell
      - name: Install Dependencies
        run: pdm install

      - name: Tests
        run: pdm run tests
